import type { Metadata } from "next";
import { Geist, Geist_Mono,Signika_Negative } from "next/font/google";
import "./globals.css";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistSignika = Signika_Negative({
  variable: "--font-geist-signika-negative",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistSignika.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
